services:
  watchtower:
    image: nickfedor/watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: '${TELEGRAM}'
      WATCHTOWER_SCHEDULE: "0 0 3 * * *"
      WATCHTOWER_NOTIFICATION_TITLE_TAG: "ansible"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
